project_id = "iuvwtzwxkgyxzcxmgrmp"

[functions.cart-sync]
verify_jwt = false

[functions.get-quotes]
verify_jwt = false

[functions.header-config]
verify_jwt = false

[functions.submit-quote]
verify_jwt = false